name: Run shimekiri notebook daily

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          # 1. Jupyterとipykernelをインストール
          pip install jupyter ipykernel
          # 2. python3 カーネルを作成
          python -m ipykernel install --user --name python3
          
          # 3. papermill, nbconvert, selenium等もインストール
          pip install papermill nbconvert gspread oauth2client pandas selenium beautifulsoup4

      - name: Set GOOGLE_CREDENTIALS to file
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run the Notebook with Papermill
        run: |
          # --kernel python3 を指定
          papermill shimekiri_gaishishukatsu_py.ipynb output.ipynb --kernel python3
